language: rust
cache: cargo
rust:
    - stable
    - beta
    - nightly
script:
    - cargo build --verbose --all
    - RUST_BACKTRACE=1 cargo test --verbose --all
matrix:
    allow_failures:
        - rust: nightly
